### ISSUE TITLE
Project does not compile

### ISSUE THREAD

**Issue by ArchieCoder** [Microsoft/Windows-appsample-lunch-scheduler#1]
Hello,

I am on VS 15.4 and the latest Fall Creative update.

Even if I update the nugets, I can't compile. Also, there is one project that does not open.

![2017-10-11_14-26-11](https://user-images.githubusercontent.com/1608424/31459209-7ef96a4a-ae90-11e7-840a-c851e5ada82d.png)

**Comment by awkoren** [comment]
Hi @ArchieCoder, do you have the latest .NET Core SDK installed? If not, you can download it here: https://www.microsoft.com/net/download/core

See https://stackoverflow.com/questions/45732236/the-current-net-sdk-does-not-support-targeting-net-standard-2-0-error-in-visua

**Comment by ArchieCoder** [comment]
I just installed .NET Core using your link (thanks).

All the projects can be loaded, but there are still errors.

![image](https://user-images.githubusercontent.com/1608424/31466405-0be1795c-aea5-11e7-923c-c3da1612659b.png)

**Comment by awkoren** [comment]
Hmm, we are having trouble reproducing this on our side. 

Can you try deleting and re-downloading the project? Maybe your state is corrupted from earlier when you were missing the latest .NET Core SDK. 

If that doesn't work, can you also try: 

- Unloading the UWP project and building. Do the other projects build successfully? 
- Removing the references to Models and Repository from the UWP project, then re-adding them.

**Comment by ArchieCoder** [comment]
I tried the above steps and it is the same result. FYI, I installed the latest FCU build today, it is the first time I'm on an insider build. Version is 16299.

Tomorrow, you can TeamViewer on my computer if you want to investigate more. Otherwise, this is not a blocker for me, I was checking the BuildCast app too to see the new changes.

**Comment by awkoren** [comment]
Hi @ArchieCoder, we spent some more time digging into this and were able to reproduce the issue. We fixed it like this:

- Launch VS installer.
- Ensure all components in the attached screenshot are checked as installed. 

![capture](https://user-images.githubusercontent.com/2568073/31841174-2bb5a7cc-b59d-11e7-9e9c-c9a3339712e4.PNG)

Please give that a try and reopen this issue if it doesn't fix your problem. We'll also make it more clear in the README these components are required.
